### ISSUE TITLE
resultado do tst test

### ISSUE THREAD

**Issue by joaoarthurbm** [daltonserey/tst#2]
No modo professor, o resultado da execução `tst test` está sendo sumarizado. Por exemplo, `tst test` dentro do diretório da atividade resulta em uma string com apenas 2 caracteres (um para o public_tests.py e outro para o acceptance_tests.py). Assim, fica mais difícil ter uma ideia detalhada do desempenho do aluno.
### Exemplo

dir: _bd/prog1-20161/soma_polinomios-v1_
`tst test`
`.. zeze_camargo.py`
`.F chitao_xororo.py`
### Como era antes (e como acho que deveria ser)

dir: _bd/prog1-20161/soma_polinomios-v1_
`tst test`
`.. ........ zeze_camargo.py`
`.. .F.F.... chitao_xororo.py`

**Comment by daltonserey** [comment]
@joaoarthurbm: Agora entendi bem o problema. De fato, é um bug. A especificação é para que o tst faça exatamente como você mencionou.

Só relembrando que como se trata de script tests (testes rodados pela execução de um script externo ao tst), o tst apenas coleta e concatena os sumários da execução de cada um dos scripts. Mas, se algum dos scripts falhar (`exit_code != 0`) o sumário é substituído por uma única exclamação -- já que não há como saber quantos testes concretos o script faria.
