### ISSUE TITLE
Integrate the tests in the new version of the tst.json

### ISSUE THREAD

**Issue by sormany** [daltonserey/tst#4]
In actual version of tst.json, not possible tests run. It's necessary to integrate the tests inside tst.json file.
For now, I'm trying to run the tests in another directory.
Other problem it's in removing plus signal of the front the pip signal. 
For sample:

```
tests:
-   category: public
-   input: |+        
    output: |
        Entrada inválida!
-   input: |
```

**Comment by daltonserey** [comment]
Hi @Sormany, could you improve your explanation? Explain what the original problem is and what is the way to fix it or the improvement suggested.

**Comment by sormany** [comment]
Ok. Let's go!
**Issue 1** - With the new tst.json file it's no possible to run tests of the problem. Because not has tests inside the file. Only log data and of the owner the activity.
**Suggest** - include the tests within tst.json file.

**Issue 2** - In the tests that are required for an empty entry, for example:

```
-   input: |+
    output: |
        Entrada inválida!
```

After running the checkout, the plus signal is removed, make it the invalid test.

```
-   input: |
    output: |
        Entrada inválida!
```

**Suggest** - For this cases, consider replace the pip signal for representation "\n". For example:

```
    input: "\n"
    output: |
        Entrada inválida!
```

**Comment by daltonserey** [comment]
@Sormany. As you said it yourself, there are clearly two issues in one. Next time, create separate issues, please.

With respect to issue number one above. It is an already planned enhancement. To make it clearer and easier to track, I created issue #6. I think it describes the same idea, please take a look.

With respect to the second issue above. It is a bug. To make it easier to track, I created it as issue #7 and tried to write a better explanation about the problem. Please check to see it is what you meant.
