### ISSUE TITLE
couldn't run command 'new'

### ISSUE THREAD

**Issue by mirnacarelli** [daltonserey/tst#5]
I successful run command checkout2. But when I try to run command new, I had this error "tst: couldn't run command 'new'".
I show here the step-by-step of the commands execution:
mirna@mirna-VirtualBox:~$ tst new mc3
tst: couldn't run command 'new'
mirna@mirna-VirtualBox:~$ tst config
user: mirnacarelli@gmail.com
url: http://244b.tst-online.appspot.com
mirna@mirna-VirtualBox:~$ tst new mc3
tst: couldn't run command 'new'
mirna@mirna-VirtualBox:~$ ls
Área de Trabalho  examples.desktop  mc2      Público
Documentos        Imagens           Modelos  Vídeos
Downloads         mc1               Música
mirna@mirna-VirtualBox:~$

**Comment by mirnacarelli** [comment]
This happened in my personal computer. The command was working in the lab machine.

**Comment by daltonserey** [comment]
Any reason for you to close this issue? It seems to that this is a real problem.

**Comment by daltonserey** [comment]
I think this has been fixed now. The tst-test command permissions were incorrect.
